name: update badges

on:
  # allows to manually run the job at any time
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          COMMIT_MESSAGE: "Updated badges" # optional
          #CREDLY_SORT: POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          CREDLY_USER: rafaraujo589 # optional, but default will use the same from github
          BADGE_SIZE: 75 # optional, 5x5 default
