name: update badges

on:
  schedule:
    # Runs at 15 UTC
    - cron: "0 0 * * *"
  # allows to manually run the job at any time
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Updated badges" # optional
          CREDLY_SORT: POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          BADGE_SIZE: 110 # optional, 110x110 default
